module.exports = {
    //hide download btn
	downloadBtnHide : 'display:none',
	//img2 css patch
	cssPatch : 'css-patch',
	//section or element hide data
	btnHide : 'display:none;',
	modalBtnHide : 'display:none;',
	modalBtnAction: ' ',
	sectionHide : ' ',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : 'display:none;',
	//navbar active
	activeAbout : 'active',
	activeWhatWeDo : '',
	activeBlogs : '',
	activeOurWork : '',
	activeCareers : '',
	activeWorkshops : '',
	activeSchoolManagementSystem: '',
	//display data
	bannerImg: 'images/about/banner.png',
	bannerTextPart1 : 'Because we love',
	bannerTextPart2 : ' what we do',
	bannerSideHead : 'Our Mission',
	bannerSidePara : 'We aim to help the clients create the future. We succeed when we make our clients successful. We innovate to find a better way—for the clients who depend on us, the customers who rely on them and the communities who count on us all. At Bolt Infotech, we develop innovative and creative products and services that provide total communication and information solutions.',
	feature1Img : 'images/about/1.png',
	feature2Img : 'images/about/2.png',
	feature3Img : 'images/about/3.png',
	feature4Img : 'images/about/4.png',
	feature5Img : 'images/about/5.png',
	feature1HeadPart1 : 'What makes us',
	feature1HeadPart2 : 'who we are today…',
	feature2HeadPart1 : 'How it',
	feature2HeadPart2 : 'begun!',
	feature3HeadPart1 : 'We provide cost effective and reliable IT support',
	feature3HeadPart2 : 'to the customers.',
	feature4HeadPart1 : 'We aim to be',
	feature4HeadPart2 : 'the preferred IT solution provider.',
	feature1Para : "At Bolt Infotech, we develop innovative and creative software and services that provide total communication and information solutions.Since 2016 we have been helping global companies and established brands reimagine their business by building impactful digital engineering solutions powered by the latest technologies. Bolt's business philosophy is to assure the highest quality product, total client satisfaction, timely delivery of solutions and the best quality/price ratio found in the industry.",
	feature2Para : 'Web design and development, custom made applications, ERPs, CRMs, e-commerce solutions, business-to-business applications, business-to-client applications, managed hosting and internet portal management are the services that we offer. Our history demonstrates our controlled and steady growth. Our approach is based on professional, technical, human and environmental standards which have evolved over time on a foundation of strong and clear business principles. All this is combined in an unfaltering commitment to our clients, our people and our shared objectives. We have started our journey as a proprietary, and in short time span of 3 years, we have helped many enterprises and startups accelerate adoption of new technologies, untangle complex issues that always emerge during digital evolution, orchestrate ongoing innovation and moving forward on this curve of growth, we got ourselves registered as Private Limited Company in the winters of 2018 and are growing with rapid pace and have proved to be a visionary and a reliable software engineering partner for various Startups and Enterprises.',
	feature3Para :"We strive to provide the best in the market through always delivering consistent quality services that exceed our customer's expectations. We are proud to conduct our business with integrity, through operating with honesty and virtue.",
	feature4Para : 'We are conscious that our support impact your operations and take responsibility for our actions. We are committed to ensuring you can count on us to get any job done, anytime.  We are committed to delivering our best efforts in order to get a job done well.',
	cardHeadPart1 : 'Why ',
	cardHeadPart2 : 'BOLT?',
	card1Img: 'images/about/6.png',
	card2Img: 'images/about/7.png',
	card3Img: 'images/about/8.png',
	card1HeadPart1: 'Client ',
	card1HeadPart2: 'First Always',
	card2HeadPart1: 'Our People ',
	card2HeadPart2 : 'Our Strength',
	card3HeadPart1: 'Quality Policy ',
	card3HeadPart2: 'Not Negotiable',
	card1Para: 'The goal is simple : relentlessly commit to your clients; be hardworking and humble; stay unconflicted in your work and uncompromising in your values. The rest will take care of itself.',
	card2Para: 'We believe that people are the key drivers of our success. Our HR Policies, therefore, focus on developing an environment that attracts and inspire excellence in people.',
	card3Para : 'Quality is never an accident; it is always the result of high intention, sincere effort, intelligent direction and skillful execution; it represents the wise choice of many alternatives.',
	belowCtah1:"Wanna Collaborate?",
	belowCtah2:"It will be fun transforming your idea digitally."
}