module.exports = {
    //hide download btn
	downloadBtnHide : 'display:none',
	//img2 css patch
	cssPatch : ' ',
	//section or element hide data
	btnHide : 'display:none;',
	modalBtnAction: 'modal-btn',
	sectionHide : 'display:none;',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : 'display:none',
	//navbar active
	activeAbout : ' ',
	activeWhatWeDo : ' ',
	activeBlogs : '',
	activeOurWork : '',
	activeCareers : 'active',
	activeWorkshops : '',
	activeSchoolManagementSystem: '',
	//button route
	btn1route : ' ',
	btn2route : ' ',
	btn3route : ' ',
	btn4route : ' ',
	btn5route : ' ',
	//button text
	btn1text : 'Get Hired!',
	btn2text : 'Get Hired!',
	btn3text : 'Get Hired!',
	btn4text : 'Get Hired!',
	btn5text : 'Get Hired!',
	//display data
	bannerImg: 'images/careers/banner.png',
	bannerTextPart1 : 'It starts with',
	bannerTextPart2 : 'ONE!',
	bannerSideHead : 'Passion to code? Come on!',
	bannerSidePara : "The secret of our success is the people we recruit – and we’re looking for the best. We’re always looking for people who can bring new perspectives to our teams. If you want to be part of a team that values your enthusiasm, passion, and creativity; if you’re seeking colleagues who are big thinkers, eager to take on fresh challenges as a team, apply below. Please don't forget to check on the tech stacks we are looking for; as of now in the list below.",
	feature1Img : 'images/careers/1.png',
	feature2Img : 'images/careers/2.png',
	feature3Img : 'images/careers/3.png',
	feature4Img : 'images/careers/4.png',
	feature5Img : 'images/careers/5.png',
	feature1HeadPart1 : 'Mobile',
	feature1HeadPart2 : 'DEVELOPER',
	feature2HeadPart1 : 'Web',
	feature2HeadPart2 : 'DEVELOPER',
	feature3HeadPart1 : 'Graphics',
	feature3HeadPart2 : 'DESIGNER',
	feature4HeadPart1 : 'Game',
	feature4HeadPart2 : 'DEVELOPER',
	feature5HeadPart1 : 'Back-end',
	feature5HeadPart2 : 'DEVELOPER',
	feature1Para : 'Have got amazing work experience on Android Development, iOS development, Java, Kotlin, Objective-C, Swift, Xcode, React Native or Flutter? Apply now! We will look into your past projects and knowledge base before giving you a call.',
	feature2Para : 'More than confident for coding backend APIs on ASP .NET, PHP, NodeJs, Python? Have you got knowledge of the latest front-end tech stacks including SASS, Advanced CSS, jQuery and HTML5? Love integrating CMS efficiently? Apply now!',
	feature3Para : 'The sky is the limit for your creativity? Have you got an amazing color sense and theming concepts? Got expertise working on Adobe CC applications? (Confident working on any one of them or more?) Provide links to your works in your Resume and Apply now!',
	feature4Para : 'Best aware of all technical aspects of the game development including challenges in implementing the core game mechanics, art, animation? Can optimize code for the best possible performance, quality, and responsiveness of games across platforms? Hit the button below.',
	cardHeadPart1 : 'Our People ',
	cardHeadPart2 : 'Philosophy',
	card1Img: 'images/careers/6.png',
	card2Img: 'images/careers/7.png',
	card3Img: 'images/careers/8.png',
	card1HeadPart1: 'Your ',
	card1HeadPart2: 'Canvas',
	card2HeadPart1: 'Tough ',
	card2HeadPart2 : 'Love',
	card3HeadPart1: 'Whole ',
	card3HeadPart2: 'Self',
	card1Para: 'Our work environment never restricts your creativity and we provide completely free canvas to you to paint and create your best picture!',
	card2Para: 'We ensure standing side by side with you with our team in all moments of Happiness and sorrow. We believe in woking togehter as a Family :)',
	card3Para : "We've built this business with the passion for innovation and a flexible approach in what we do. That's why we keep our eyes and ears open for smart people who get things done."
}