module.exports = {
    learnMoreRouteCloud : '/learnMoreSoftware',
	btnHide : 'display:none;',
	hide: 'display:none;',
	activeWebDevelopment : ' ',
	activeMobileDevelopment : ' ',
	activeGraphicsDesign : ' ',
	activeMobileGames: ' ',
	activeCustomizedSoftware : 'active',
	topBannerImage: 'images/customized/custom-banner.jpg',
	imgDesktop:'images/customized/1.jpg',
	imgMobile: 'images/customized/1-mobile.jpg',
	nav2head: 'System tailored as per your needs',
	nav2para: 'We provide high quality, cost-effective and reliable software development services that match your specific needs, budget and timeframe. From simple customizations to full-cycle software development that matches your vision, we have got the experience to deliver.No matter what type of your work you do, Bolt Infotech’s customized software development will fulfill your needs.',
	appsForImg: 'images/customized/2.jpg',
	appsForHead: 'Software that makes your business and work convinient.',
	appsForIoneClass:'fas fa-smile-beam',
	appsForH3one: 'User Friendly',
	appsForPone:'Our software confidently works across all popular browsers, OSes and mobile platforms, scales to millions of users and delivers immaculate UX through a clear, logical layout.',
	appsForItwoClass:'fas fa-dumbbell',
	appsForH3two: 'Robust',
	appsForPtwo: 'Tell us your needs, desired functionality, the business methods used, and we can build you the software solutions. Our software is scalable and flexible enough for you to easily adapt down the road.',
	appsForIthreeClass:'fas fa-tools',
	appsForH3three: 'Maintainable',
	appsForPthree: 'We begin every relationship with an in-depth discussion about the short and long-term desires for your project and take its all responsibility',
	iosImgDesktop: 'images/customized/3.jpg',
	iosHeadOne: 'Software for your organization',
	iosImgMobile: 'images/customized/3-mobile.jpg',
	iosHeadTwo: 'Software for your organization',
	iosPara: 'Let’s begin a conversation about your new ideas or on-going projects that need the fresh and innovative touch of our expert developers. This ranges from simple custom app development to complicated, long-term contracts. We assist clients throughout the product development lifecycle, from product research and new product development to quality assurance.',
	liIosOne: 'School Management System',
	liIosTwo:'Accounts Management System',
	liIosThree:'GST and Taxations',
	liIosFour:'Custom ERP',
	cloudImg:'images/customized/4.jpg',
	cloudHead: 'Efficient tools, for best results',
	cloudPara: 'Our Custom Software Development Services leverage the technical expertise of our professionals who are empowered with latest technology software and tools, to offer customized applications of various flavours including business intelligence solutions, e-business solutions, custom application development and CRM solutions.',
	cloudIoneclass: 'fab fa-microsoft tech-type',
	cloudItwoclass: 'fab fa-node tech-type',
	cloudIthreeclass: 'fab fa-php tech-type',
	cloudIfourclass: 'fab fa-python tech-type',
	liCloudOne: '.NET',
	liCloudTwo: 'NodeJS',
	liCloudThree: 'php',
	liCloudFour: 'Python',
	portfolioImg1:'images/p1.png',
	portfolioImg2:'images/p2.png',
	portfolioImg3:'images/p3.png',
	workedHead: 'Designed for apps of Different Categories',
	workedIoneClass: 'fas fa-water',
	workedItwoClass: 'fas fa-clinic-medical',
	workedIthreeClass: 'fas fa-cookie-bite',
	workedIfourClass: 'fas fa-home',
	workedIfiveClass: 'fas fa-headphones',
	workedIsixClass: 'fas fa-book-open',
	portfolioHead: 'Recent Projects',
	portfolioPara: 'We are an elite team of product managers, software architects, and developers who partner with business executives to build their next successful product. Whether you are engineering a new product or reinventing an existing one, we can help bring your vision to life. Your idea deserves the very best chance of success. This means having excellent aesthetics combined with functional, scalable, and maintainable code. Why compromise?',
	portfolioHead1: 'HELP',
	portfolioHead2: 'COZY',
	portfolioHead3: 'GURU',
	portfolioPara1: 'Get all your household services at your doorsteps. Order online anytime, anyplace and it will be there.',
	portfolioPara2: 'Order your food online form your favourite Restaurant or even form large number of Home Cooks.',
	portfolioPara3: 'Click the photo of your doubts about Maths and get its result in just a few seconds!',
	client1Img:'images/lady-img.jpg',
	client2Img:'images/learnMore/man-img.jpg',
	client1Name: 'Beverly, Illinois',
	client2Name: 'Beverly, Illinois',
	client1Feedback: '“They listened to my ideas, made recommendation and helped me make the app that I wanted to make.”',
	client2Feedback: '“They added life to my idea, Digitally!”'
}