module.exports = {
    learnMoreRouteCloud : '/learnMoreDesign',
	btnHide : 'display:none;',
	hide: 'display:none;',
	activeWebDevelopment : ' ',
	activeMobileDevelopment : ' ',
	activeGraphicsDesign : 'active',
	activeMobileGames: ' ',
	activeCustomizedSoftware : ' ',
	topBannerImage: 'images/graphics/design-banner.jpg',
	imgDesktop:'images/graphics/graphic-background-desktop.jpg',
	imgMobile: 'images/graphics/graphic-background-mobile.jpg',
	nav2head: 'First Impression should be the best!',
	nav2para: "There's no limit to what you can get designed at Bolt Infotech. Whether you're looking for a spectacular new logo or Ui Ux design or some stunning flyers, the talented community of designers here can make it happen. We have high quality designers who deliver only the best graphic design services. Find the right design service for you below and get design you'll love today!",
	appsForImg: 'images/graphics/2 real.jpg',
	appsForHead: 'User Interface of the apps speak and express!',
	appsForIoneClass:'fas fa-bolt',
	appsForH3one: 'Clear',
	appsForPone:'Our community of professional designers are ready to create the perfect graphic for you. Simply, start a graphic design project today and get a graphic you’ll love.',
	appsForItwoClass:'far fa-grin-stars',
	appsForH3two: 'Attractive',
	appsForPtwo: 'Receive unique designs from around the world within hours. Select and approve your favorite design. Tell us what you need, complete your creative brief in a matter of minutes.',
	appsForIthreeClass:'fas fa-tablet-alt',
	appsForH3three: 'Responsive',
	appsForPthree: 'We take the essence of your business and delivers it to a whole new level of importance—unrestrained by convention. UI which we design are always suitable for maximum devices around.',
	iosImgDesktop: 'images/graphics/3.jpg',
	iosHeadOne: 'We take care when we desgin',
	iosImgMobile: 'images/graphics/3-mobile-.jpg',
	iosHeadTwo: 'We take care when we DESIGN',
	iosPara: "Need to make a lasting impression? The right combination of colors, shapes and words will define your brand. Get the perfect logo and ensure your branding hits the spot with these services.Looking to make a mark on the world wide web? Whether you need a new design for a custom built website or a design for a popular CMS platform you'll find the perfect web design with our design services.",
	liIosOne: 'Concise',
	liIosTwo:'Consistent',
	liIosThree:'Efficient',
	liIosFour:'Familiar',
	cloudImg:'images/graphics/4.jpg',
	cloudHead: 'Experience, not just Interface!',
	cloudPara: "Really need some design inspiration? Someone who can use their creative skills to make a design that will really pop? These graphic design services may be just what you're looking for.Need some walking advertising? A little promotional gear for the team manning the tradeshow booth? Get custom apparel, mugs or caps from our professional designers.",
	cloudIoneclass: 'fas fas fa-tape tech-type',
	cloudItwoclass: 'fas fa-pencil-ruler tech-type',
	cloudIthreeclass: 'fas fa-ruler-combined tech-type',
	cloudIfourclass: 'fas fa-crop-alt tech-type',
	liCloudOne: 'Low Fidelity Wireframe',
	liCloudTwo: 'High Fidelity Wireframe',
	liCloudThree: 'UI',
	liCloudFour: 'UX',
	portfolioImg1:'images/p1.png',
	portfolioImg2:'images/p2.png',
	portfolioImg3:'images/p3.png',
	workedHead: 'Designed for apps of Different Categories',
	workedIoneClass: 'fas fa-water',
	workedItwoClass: 'fas fa-clinic-medical',
	workedIthreeClass: 'fas fa-cookie-bite',
	workedIfourClass: 'fas fa-home',
	workedIfiveClass: 'fas fa-headphones',
	workedIsixClass: 'fas fa-book-open',
	portfolioHead: 'Recent Projects',
	portfolioPara: 'We are an elite team of product managers, software architects, and developers who partner with business executives to build their next successful product. Whether you are engineering a new product or reinventing an existing one, we can help bring your vision to life. Your idea deserves the very best chance of success. This means having excellent aesthetics combined with functional, scalable, and maintainable code. Why compromise?',
	portfolioHead1: 'HELP',
	portfolioHead2: 'COZY',
	portfolioHead3: 'GURU',
	portfolioPara1: 'Get all your household services at your doorsteps. Order online anytime, anyplace and it will be there.',
	portfolioPara2: 'Order your food online form your favourite Restaurant or even form large number of Home Cooks.',
	portfolioPara3: 'Click the photo of your doubts about Maths and get its result in just a few seconds!',
	client1Img:'images/lady-img.jpg',
	client2Img:'images/learnMore/man-img.jpg',
	client1Name: 'Beverly, Illinois',
	client2Name: 'Beverly, Illinois',
	client1Feedback: '“They listened to my ideas, made recommendation and helped me make the app that I wanted to make.”',
	client2Feedback: '“They added life to my idea, Digitally!”'
}