module.exports = {
    topBannerImage : 'images/learnMoreWebDev/web-banner.jpg',
	topHead : 'Delivering Right Web Development Solutions',
	topPara : 'The outputs of our web development services are creating lasting impressions, both visually and interactively. It can transcend the physical and start to connect with people in a way that is transformational on the web. Typically, we build dynamic experiences and a wide variety of web development.',
	hireImg: 'images/learnMoreWebDev/middle-upper.png',
	hireHead : 'Hire our Web developers',
	hirePara: 'We design functional interfaces for an engaging and secure digital experience that helps to boost the brand’s performance. Each website and app relies on an instinctive UX/UI design which helps in increasing the user traffic. We are sensitive to the latest trends and as responsive as our design – helping you to engage the users in a digital landscape. We work with close-coordination with the customers, to ensure flexible & cost effective web development services. Our web designers after a thorough analysis of your business, will provide you with a customized web design and development solution which will meet your business requirements.',
	displaySection : 'display:none;',
	cta : 'Get in touch',
	ctaLink : 'contactUs',
    ctaLink1 : 'contactUs',
	liImg1 :'images/learnMore/1.png',
	liImg2 :'images/learnMore/2.png',
	liImg3 :'images/learnMore/3.png',
	liImg4 :'images/learnMore/4.png',
	liHead1 : 'Agile development',
	liHead2 : 'Full commitmen',
	liHead3 : 'Coding on your budget',
	liHead4 : 'Extended Support',
	liPara1 : 'Following the standards of agile development, we hold regular meetings and provide you with everything on a daily basis. You have full control over the procedure.',
	liPara2 : 'Majority of our business originates from referrals. We will strive to get another satisfied client and we trust that you will remain with us for a long period of time.',
	liPara3 : 'Regardless of the phenomenal quality, the expenses are much lower. Furthermore, we update you with the detailed budget, so you can recognize precisely, what you are paying for.',
	liPara4 : 'Our technical team will make sure that you never come across any issues after completion of the project. In case you face any issue, we are just a tap away.'
}