module.exports = {
    topBannerImage : 'images/learnMoreDesign/design-banner.jpg',
	topHead : 'Your Marketing Need Through Innovative Graphic',
	topPara : 'Websites, businesses and brands are all much more than just words and products – they’re also images and art. Graphic design is an integral part of any business and that’s as true for your company’s image and your marketing. Attracting visitors and converting sales is often influenced by graphics.',
	hireImg: 'images/learnMoreDesign/middle-upper.png',
	hireHead : 'Hire our Graphics Designers',
	hirePara: 'Working with our talented designers and developers, you can create eye-catching designs for your site that will help tell the story of your products. Colorful, high-resolution images, engaging videos and illustrative graphics can help potential buyers better understand your products and services and help them see – literally – the benefits they offer. Success online is multifaceted in the modern age. While sites rich in text can help you be found within search results, attracting visitors and converting sales is often influenced by the audio-visual impact.Graphic design is an integral part of any business and that’s as true for your company’s image and your marketing.',
	liImg1 :'images/learnMore/1.png',
	liImg2 :'images/learnMore/2.png',
	liImg3 :'images/learnMore/3.png',
	liImg4 :'images/learnMore/4.png',
	liHead1 : 'Logo & Branding',
	liHead2 : 'Web Design Services',
	liHead3 : 'Art & Illustration',
	liHead4 : 'Print Design Services',
	liPara1 : 'The right combination of colors, shapes and words will define your brand. Get the perfect logo and ensure your branding hits the spot with these services.',
	liPara2 : "Whether you need a new design for a custom built website or a design for a popular CMS platform you'll find the perfect web design with these design services.",
	liPara3 : "Whether you need a mascot designed for your sporting team or a piece of custom wall art you'll find what you need with these design services.",
	liPara4 : "Don't make the mistake of having a mistake - get the design right the first time, whether it's a flyer, poster or sticker. Check out all our print design services."
}