module.exports = {
    topBannerImage : 'images/learnMoreSoftware/custom-banner.jpg',
	topHead : 'Top-Grade Custom Software Development',
	topPara : 'We build frontline software solutions that enable enterprises to unlock innovation and make a difference in the tech world. Leverage our low-risk approach and development accelerators to propel your digital transformation and ensure a competitive edge.',
	hireImg: 'images/learnMoreSoftware/middle-upper.png',
	hireHead : 'Hire our Back-End developers',
	hirePara: "In today's dynamic and fast changing world, every company wishes to stay ahead or at least on par with its competitors. This is possible only if the businesses have the right strategies and systems in place. Custom software applications automate and streamline the processes in an organization, thus saving a huge amount of time and cost while increasing efficiency. From concept to code, development to deployment, we provides custom IT solutions that accelerate workflows, optimize operations and boost revenues. Whether you're looking to develop a new app for your business or improve your existing software environment, we offer the bespoke software development services you require.",
	displaySection : 'display:none;',
	cta : 'Get in touch',
	ctaLink : 'contactUs',
    ctaLink1 : 'contactUs',
	liImg1 :'images/learnMore/1.png',
	liImg2 :'images/learnMore/2.png',
	liImg3 :'images/learnMore/3.png',
	liImg4 :'images/learnMore/4.png',
	liHead1 : 'Result-Driven Approach',
	liHead2 : 'Value Proposition',
	liHead3 : 'Custom-Built Solutions',
	liHead4 : 'Cost-Effective Service',
	liPara1 : 'We strategize result-driven solutions with advanced and proven methodologies.',
	liPara2 : 'The end-product is assured to add value to your business and deliver it to users.',
	liPara3 : 'For every unique idea, we offer flexibility to suit your business needs.',
	liPara4 : 'Be it a low-budget startup or a billion-dollar venture, we ensure cost-effectiveness.'
}