module.exports = {
    topBannerImage : 'images/learnMore/top-banner.jpg',
    topHead : 'Give Your Business App an iOS Advantage',
    topPara : 'Our extremely experienced iOS development team specializes in producing custom & secure iPhone app solutions according to market requirements and measure to meet user demands. Our expert developers know the critical aspects of iPhone app development and can help your dreams come true.',
    hireImg: 'images/learnMore/middle-upper.png',
    hireHead : 'Hire our iOS developers',
    hirePara: 'Our iPhone app developers are well equipped with the latest iOS technologies and versions and have a strong platform experience too. We deliver custom applications that are tailored to fit the different requirements of the clients. Our developers are known for  innovation and creativity for apps developed on iOS that has transformed the commercial landscapes as enterprises over the world. The iPhone applications developed are extremely scalable and strong to enable global businesses for optimal productivity. We follow global iOS development processes to produce a broad range of iPhone, iWatch, iPad based mobile applications for diverse business verticals.',
    liImg1 :'images/learnMore/1.png',
    liImg2 :'images/learnMore/2.png',
    liImg3 :'images/learnMore/3.png',
    liImg4 :'images/learnMore/4.png',
    liHead1 : 'iOS App Customization',
    liHead2 : 'Reach Elite Class',
    liHead3 : 'Get the Latest App',
    liHead4 : 'Attractive AI, Ultimate UX',
    liPara1 : 'Get a customized iOS app with attractive UI and enhanced security for addressing business requirements while targeting niche iOS device users',
    liPara2 : 'Get a customized iOS app with attractive UI and enhanced security for addressing business requirements while targeting niche iOS device users',
    liPara3 : 'Get a customized iOS app with attractive UI and enhanced security for addressing business requirements while targeting niche iOS device users',
    liPara4 : 'Get a customized iOS app with attractive UI and enhanced security for addressing business requirements while targeting niche iOS device users'
}