module.exports = {
    learnMoreRouteCloud : '/learnMoreGames',
	btnHide : 'display:none;',
	hide: 'display:none;',
	activeWebDevelopment : ' ',
	activeMobileDevelopment : ' ',
	activeGraphicsDesign : ' ',
	activeMobileGames: 'active',
	activeCustomizedSoftware : ' ',
	topBannerImage: 'images/games/game-banner.jpg',
	imgDesktop:'images/games/1.jpg',
	imgMobile: 'images/games/1-mobile.jpg',
	nav2head: 'Game that feels real!',
	nav2para: 'Our expert  developers follow some of the newest development methodologies for delivering next level mobile gaming experience. We also know the vital of UI/UX designing when it comes to mobile games development. That is why our UI/UX professionals pay special focus for offering mobile game designs that can improve the complete look and feel of the game on the mobile devices.',
	appsForImg: 'images/games/2.jpg',
	appsForHead: 'Games that are developed not just to play but to experience!',
	appsForIoneClass:'fas fa-dice',
	appsForH3one: '2D Games',
	appsForPone:'With a dedicated team of game developers, concept artists, we assists you in all range of gaming requirements. We can develop completely engaging app that requires 100% commitment.',
	appsForItwoClass:'fas fa-gamepad',
	appsForH3two: '3D Games',
	appsForPtwo: 'With a dedicated team of game developers, concept artists, we assists you in all range of gaming requirements. We can develop completely engaging app.',
	appsForIthreeClass:'fas fa-gavel',
	appsForH3three: 'VR Games',
	appsForPthree: 'Our VR developers can bring your VR game app ideas to life, boosting marketing opportunities, in-app purchases, and ads to monetize via games.',
	iosImgDesktop: 'images/games/3.jpg',
	iosHeadOne: 'VR Games',
	iosImgMobile: 'images/games/3-mobile.jpg',
	iosHeadTwo: 'VR Games',
	iosPara: 'VR is a disruptive technology proving to be a powerful sales and marketing tool for all industries. We have highly skilled and experienced VR app developers who can create experiences and environments that don’t even exist, making you feel as if you really are ‘within’ that world. Our VR studio team is a combination of creative staff and technical professionals.',
	liIosOne: 'Believable',
	liIosTwo:'Interactive',
	liIosThree:'Explorable',
	liIosFour:'Immersive',
	cloudImg:'images/games/4.jpg',
	cloudHead: 'Efficient tools, for best results',
	cloudPara: 'Gaming and entertainment has become an essential part in mobile and web industry, turning into a rapidly growing industry worth billions of dollars globally. Millions of smartphone users and tech-savvy people spend their time playing games on their mobiles, laptops or tablets. Developing unique and memorable games requires technical expertise and creative minds.',
	cloudIoneclass: 'fas fa-dice-d6 tech-type',
	cloudItwoclass: 'fas fa-puzzle-piece tech-type',
	cloudIthreeclass: 'fas fa-hand-scissors tech-type',
	cloudIfourclass: 'fas fa-headset tech-type',
	liCloudOne: 'Unity',
	liCloudTwo: 'SpriteKit',
	liCloudThree: 'Corona',
	liCloudFour: 'Cocos2D',
	portfolioImg1:'images/p1.png',
	portfolioImg2:'images/p2.png',
	portfolioImg3:'images/p3.png',
	workedHead: 'Designed for apps of Different Categories',
	workedIoneClass: 'fas fa-water',
	workedItwoClass: 'fas fa-clinic-medical',
	workedIthreeClass: 'fas fa-cookie-bite',
	workedIfourClass: 'fas fa-home',
	workedIfiveClass: 'fas fa-headphones',
	workedIsixClass: 'fas fa-book-open',
	portfolioHead: 'Recent Projects',
	portfolioPara: 'We are an elite team of product managers, software architects, and developers who partner with business executives to build their next successful product. Whether you are engineering a new product or reinventing an existing one, we can help bring your vision to life. Your idea deserves the very best chance of success. This means having excellent aesthetics combined with functional, scalable, and maintainable code. Why compromise?',
	portfolioHead1: 'HELP',
	portfolioHead2: 'COZY',
	portfolioHead3: 'GURU',
	portfolioPara1: 'Get all your household services at your doorsteps. Order online anytime, anyplace and it will be there.',
	portfolioPara2: 'Order your food online form your favourite Restaurant or even form large number of Home Cooks.',
	portfolioPara3: 'Click the photo of your doubts about Maths and get its result in just a few seconds!',
	client1Img:'images/lady-img.jpg',
	client2Img:'images/learnMore/man-img.jpg',
	client1Name: 'Beverly, Illinois',
	client2Name: 'James, USA',
	client1Feedback: '“They listened to my ideas, made recommendation and helped me make the app that I wanted to make.”',
	client2Feedback: '“They added life to my idea, Digitally!”'
}