module.exports = {
    //hide download btn
	downloadBtnHide : 'display:none',
	//img2 css patch
	cssPatch : ' ',
	//section or element hide data
	btnHide : 'display:none',
	modalBtnAction: ' ',
	modalBtnHide : 'display:none;',
	sectionHide : ' ',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : 'display:none',
	//navbar active
	activeAbout : ' ',
	activeWhatWeDo : ' ',
	activeBlogs : '',
	activeOurWork : 'active',
	activeCareers : '',
	activeWorkshops : '',
	activeSchoolManagementSystem: '',
	//display data
	bannerImg: 'images/ourWork/banner.png',
	bannerTextPart1 : 'Whatever',
	bannerTextPart2 : 'IT takes!',
	bannerSideHead : 'Recent Developments',
	bannerSidePara : 'Our success lies in changing the game for our clients brands. By focusing on customer outcomes, we build beautiful, engaging experiences that drive real business results. We’re inspired by our clients and work to advance their business by innovating everything digital. We’re endless innovators, constantly looking for new ways to connect the dots and connect people.',
	feature1Img : 'images/ourWork/1.png',
	feature2Img : 'images/ourWork/2.png',
	feature3Img : 'images/ourWork/3.png',
	feature4Img : 'images/ourWork/4.png',
	feature1HeadPart1 : 'Project',
	feature1HeadPart2 : 'HELP',
	feature2HeadPart1 : 'Project',
	feature2HeadPart2 : 'COZY',
	feature3HeadPart1 : 'Project',
	feature3HeadPart2 : 'BYEPLASTIK',
	feature4HeadPart1 : 'Project',
	feature4HeadPart2 : 'GURU',
	feature1Para : 'HELP, Smartphone application designed to improve the quality of life for you by providing household services ranging from caring (babies, toddlers, children, seniors and sick people), washing and ironing, cooking, shopping, driver, cleaning the house, gardening to carpentry .',
	feature2Para : 'COZY is a startup to help provide all the services needed on one platform, at the start of the service we provide services between restaurant owners, and anyone can become a chef (home cooking) and sell and promote their dishes to culinary lovers.',
	feature3Para : 'BYEPLASTIK is an environment-friendly project to reduce plastic waste in nature by reusing the plastic bottles. This is an e-commerce application where one can simply order the products and get it delivered right at their desired venue.',
	feature4Para : 'GURU is an application for the students to click the pictures of the questions they are having difficulty in and upload it to get its most appropriate solution in seconds. It also contains complete solution of all popular books and previous year question papers.',
	cardHeadPart1 : 'Work culture @ ',
	cardHeadPart2 : 'BOLT',
	card1Img: 'images/ourWork/6.png',
	card2Img: 'images/ourWork/7.png',
	card3Img: 'images/ourWork/8.png',
	card1HeadPart1: 'Experience  ',
	card1HeadPart2: '& Expertise',
	card2HeadPart1: 'Unparalleled ',
	card2HeadPart2 : 'Services',
	card3HeadPart1: 'Optimized ',
	card3HeadPart2: 'Results',
	card1Para: 'We are made up of bold and creative thinkers that from every walk of life. Our open culture drives success for our clients and our focus on company wide inclusion creates a great opportunity for our teams',
	card2Para: 'We’re inspired by our clients and work to advance their business by innovating everything digital. We’re endless innovators, constantly looking for new ways to connect the dots and connect people.',
	card3Para : 'Customer satisfaction, openness, innovation, teamwork and growth, are the core values behind our company, and continue to reflect who we are, how we work, and what we strive for.',
	belowCtah1:"Wanna Collaborate?",
	belowCtah2:"It will be fun transforming your idea digitally."
}