module.exports = {
    topBannerImage : 'images/products/banner.png',
	topHead : 'Smart and Scalable Software Solutions',
	topPara : 'The key to making a great Software is to find programmers with both technical and artistic skills. This means your preferred programmer should know all aspects of programming but still be able to render artistic design for the Software. Build your Software fast and easy with us.',
	hireImg: 'images/products/school mgmt.png',
	hireHead : 'School Management System',
    hirePara: 'This is a Web Application, designed to maintain the complete records of various important data in the School; including Student Report, Fee Collection Report, Defaulter Report, Fee Deposit Report, Deleted Receipt Report, Expense Voucher Report, Deleted Expense Voucher Report, Salary Report, DayBook Report, Employee Report and Employee Attendance Report.',
    hireImg1: 'images/products/coaching mgmt.png',
	hireHead1 : 'Coaching Management System',
    hirePara1: 'This is a Web Application, designed to maintain the complete records of various important data for your Coaching Institution. It have got the features to keep track of Study Material and Tests that you can design for students. It also keeps track of enrolled students and their fee status. We are always up for adding the customized features to the software as per your requirements.',
    displaySection : ' ',
	liImg1 :'images/learnMore/1.png',
	liImg2 :'images/learnMore/2.png',
	liImg3 :'images/learnMore/3.png',
	liImg4 :'images/learnMore/4.png',
	liHead1 : 'Core Developers',
	liHead3 : 'Deployment on Google Play',
	liHead2 : 'In-House Coding',
	liHead4 : 'Agile Dev Process',
	liPara1 : 'We only assign core Android app developers for your business projects. They hold extensive experience in building applications for all Android smart devices.',
	liPara2 : 'All project-related codes are built, tested, and delivered from our advanced development center. We never outsource the codes to any third party developers, ever.',
	liPara3 : 'Our dedicated team handles the custom application submission to the Google Play Store. Our services include app listing, icons, descriptions, and more.',
	liPara4 : 'To minimize project risks & uncertainty and maximize performance efficiency, we incorporate & follow a custom agile process.'
}