module.exports = {
    //hide download btn
	downloadBtnHide : 'display:none',
	//img2 css patch
	cssPatch : '',
	//section or element hide data
	btnHide : 'display:none;',
	modalBtnAction: 'modal-btn-demo-link',
	sectionHide : ' ',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : ' ',
	//navbar active
	activeAbout : ' ',
	activeWhatWeDo : ' ',
	activeBlogs : '',
	activeOurWork : '',
	activeCareers : '',
	activeWorkshops : '',
	activeSchoolManagementSystem: 'active',
	//button route
	btn1route : ' ',
	btn2route : ' ',
	btn3route : ' ',
	btn4route : ' ',
	btn5route : ' ',
	//button text
	btn1text : 'Play Store Link',
	btn2text : 'DEMO Panel',
	btn3text : 'DEMO Panel',
	btn4text : 'DEMO Panel',
	btn5text : 'DEMO Panel',
	btn6text : 'DEMO Panel',
	btn7text : 'DEMO Panel',
	btn8text : 'DEMO Panel',
	//display data
	bannerImg: 'images/sms/banner.png',
	bannerTextPart1 : 'School',
	bannerTextPart2 : 'Management System',
	bannerSideHead : 'School Management Solution',
	bannerSidePara : "This is a Mobile Application with web based admin panel, designed to support Online Classes and School Management.It helps to maintain the complete records of various important data in the School; including Student Report, Fee Collection Report, Defaulter Report, Fee Deposit Report, Deleted Receipt Report, Expense Voucher Report, Deleted Expense Voucher Report, Salary Report, DayBook Report, Employee Report and Employee Attendance Report.",
	feature1Img : 'images/sms/1.png',
	feature2Img : 'images/sms/2.png',
	feature3Img : 'images/sms/3.png',
	feature4Img : 'images/sms/4.png',
	feature5Img : 'images/sms/5.png',
	feature1HeadPart1 : 'Student',
	feature1HeadPart2 : 'Mobile App',
	feature2HeadPart1 : 'Customized',
	feature2HeadPart2 : 'SMS Alerts',
	feature3HeadPart1 : 'Expense/Fee',
	feature3HeadPart2 : 'Management',
	feature4HeadPart1 : 'Staff',
	feature4HeadPart2 : 'Attendance/Payroll Management',
	feature5HeadPart1 : 'Student ',
	feature5HeadPart2 : 'Register',
	feature1Para : 'Schedule your upcoming classes, share the Course structure and related notifications to all the students in one click with the Mobile app. We have tried to make it fast and efficient Student-School communication tool. With simple and self explanatory User Interface of the app, we make it more convenient for parent and child to take the most benefit out of it, and with the Highly customizable admin panel, we provide controls to each and every bits of the app to the School Authorities.',
	feature2Para : 'Got an information to circulate? Send it to all registered students in one click. Its easy with this software. It also have got feature to send SMS to a specific student or to a specific group only.  And yes, we are open to adding more features as per requirements.',
	feature3Para : 'Keep complete record of fee submitted by students. Define your rules for fee submission, Enter the fee amount class-wise and mention the overhead charges on exceeding the date limits and the software ensures the correct amount is displayed as per the dates decided in the rules. Print the receipt with all details in one click.Keep adding various expense details with complete descriptions of Bills and Vouchers with the software. You get the options to view the expenses incurred in a given period of time. Edit or delete the records if needed. Feel free to ask us for any feature in the segment that you think the system at your school requires.',
	feature4Para : 'The software comes with multiple options to simply and efficiently manage the attendance and payroll of the employees at your organization. It have got features to manage the salary and loans granted on the name of given staff. View/Print the compensation break-ups and salary reports in one click.',
	feature5Para : 'Keep records of each and every student and search it out easily according to various parameters/filters when required. Software provide features to look into fee records of each student easily and calculate the dues most conveniently.Features available to View/Print the complete student record in one click.',
	cardHeadPart1 : 'Exciting ',
	cardHeadPart2 : 'Features',
	card1Img: 'images/sms/6.png',
	card2Img: 'images/sms/7.png',
	card3Img: 'images/sms/8.png',
	card1HeadPart1: 'Multiple ',
	card1HeadPart2: 'User Control',
	card2HeadPart1: 'Multiple ',
	card2HeadPart2 : 'Board/Stream Support',
	card3HeadPart1: 'Audit ',
	card3HeadPart2: 'Logging',
	card1Para: 'Allow more than one admin to manage the records in the software. Even we can have options to prevent controls over specific module(s) depending upon type of admin.',
	card2Para: 'The software is designed with generic features that can always be customized according to the set of rules of administration defined by your Affiliating Body.',
	card3Para : "Software keeps complete log with date/time for any data entry done and edits/deletes made for any record, so as to ensure no unwanted record variation is made.",
	belowCtah1:"Interested in the Product?",
	belowCtah2:"Contact us for demo login credentials"
}