module.exports = {
    learnMoreRouteCloud : '/learnMoreWebDev',
	btnHide : 'display:none;',
	hide: 'display:none;',
	activeWebDevelopment : 'active',
	activeMobileDevelopment : ' ',
	activeGraphicsDesign : ' ',
	activeMobileGames: ' ',
	activeCustomizedSoftware : ' ',
	topBannerImage: 'images/web/web-banner.jpg',
	imgDesktop:'images/web/custom-web-development-desktop.jpg',
	imgMobile: 'images/web/custom-web-development-mobile.jpg',
	nav2head: 'We Develop user friendly Web Apps',
	nav2para: 'Count on our talented team with exceptional web development experience to establish your brand, automatize processes, collaboration or just about anything that you can think on the web. We hand-hold you at every single step while we create custom web solutions for you – be it during discovery, definition, design, development or deployment.',
	appsForImg: 'images/web/e-Commerce-desktop.jpg',
	appsForHead: 'We collaborate to develop SEO friendly Web Apps for',
	appsForIoneClass:'fas fa-user',
	appsForH3one: 'Individuals',
	appsForPone:'We provide you Services bringing the most satisfactory outcomes and help your business to grow, creating most interactive websites in minimum time.',
	appsForItwoClass:'fas fa-city',
	appsForH3two: 'Organizations',
	appsForPtwo: 'We work with numerous enterprise technologies to provide highly customized, scalable and integrated solutions to digitally transform your business.',
	appsForIthreeClass:'fas fa-lightbulb',
	appsForH3three: 'Creators',
	appsForPthree: 'We design cost-effective web solutions for you so that you get a better chance to showcase your skills digitally and can make the most productive outcome of it.',
	iosImgDesktop: 'images/web/Backend-&-APIs-desktop.jpg',
	iosHeadOne: 'Backend-&-APIs',
	iosImgMobile: 'images/web/Backend-&-APIs-mobile.jpg',
	iosHeadTwo: 'Backend-&-APIs',
	iosPara: 'Back-end acts as an invisible backbone that connects various critical parts of an application while integrating the entire application together. For us, the key priorities for web backend development are security, accuracy, redundancy, and of course performance! We provide comprehensive back-end development expertise, which makes sure your foundation holds strong.',
	liIosOne: 'Mobile CMS',
	liIosTwo:'Authentication Services',
	liIosThree:'Web app servers',
	liIosFour:'App Engagements with push',
	cloudImg:'images/web/CMS-desktop.jpg',
	cloudHead: 'CMS',
	cloudPara: 'Content management systems (CMS) that we deliver are easy to update and manage. Without any technical knowledge, you can update your website easily. You can update the content, images and almost everything on your website. We make sure that you get full control over your website. ',
	cloudIoneclass: 'fab fa-wordpress tech-type',
	cloudItwoclass: 'fab fa-joomla tech-type',
	cloudIthreeclass: 'fab fa-drupal tech-type',
	cloudIfourclass: 'fab fa-typo3 tech-type',
	liCloudOne: 'Wordpress',
	liCloudTwo: 'Joomla',
	liCloudThree: 'Drupal',
	liCloudFour: 'TYPO3',
	portfolioImg1:'images/p1.png',
	portfolioImg2:'images/p2.png',
	portfolioImg3:'images/p3.png',
	workedHead: 'Developed Web Apps of Different Categories',
	workedIoneClass: 'fas fa-water',
	workedItwoClass: 'fas fa-clinic-medical',
	workedIthreeClass: 'fas fa-cookie-bite',
	workedIfourClass: 'fas fa-home',
	workedIfiveClass: 'fas fa-headphones',
	workedIsixClass: 'fas fa-book-open',
	portfolioHead: 'Recent Projects',
	portfolioPara: 'We are an elite team of product managers, software architects, and developers who partner with business executives to build their next successful product. Whether you are engineering a new product or reinventing an existing one, we can help bring your vision to life. Your idea deserves the very best chance of success. This means having excellent aesthetics combined with functional, scalable, and maintainable code. Why compromise?',
	portfolioHead1: 'HELP',
	portfolioHead2: 'COZY',
	portfolioHead3: 'GURU',
	portfolioPara1: 'Get all your household services at your doorsteps. Order online anytime, anyplace and it will be there.',
	portfolioPara2: 'Order your food online form your favourite Restaurant or even form large number of Home Cooks.',
	portfolioPara3: 'Click the photo of your doubts about Maths and get its result in just a few seconds!',
	client1Img:'images/lady-img.jpg',
	client2Img:'images/learnMore/man-img.jpg',
	client1Name: 'Beverly, Illinois',
	client2Name: 'Beverly, Illinois',
	client1Feedback: '“They listened to my ideas, made recommendation and helped me make the app that I wanted to make.”',
	client2Feedback: '“They added life to my idea, Digitally!”'
}