module.exports = {
    //hide download btn
	downloadBtnHide : 'display:none',
	//img2 css patch
	cssPatch : ' ',
	//section or element hide data
	modalBtnHide : 'display:none;',
	modalBtnAction: ' ',
	sectionHide : ' ',
	btnHide : ' ',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : ' ',
	//navbar active
	activeAbout : ' ',
	activeWhatWeDo : 'active',
	activeBlogs : '',
	activeOurWork : '',
	activeCareers : '',
	activeWorkshops : '',
	activeSchoolManagementSystem: '',
	//button route
	btn1route : '/mobileDevelopment',
	btn2route : '/webDevelopment',
	btn3route : '/graphicsDesign',
	btn4route : '/mobileGames',
	btn5route : '/customizedSoftware',
	//button text
	btn1text : 'Learn More',
	btn2text : 'Learn More',
	btn3text : 'Learn More',
	btn4text : 'Learn More',
	btn5text : 'Learn More',
	//display data
	bannerImg: 'images/whatWeDo/banner.png',
	bannerTextPart1 : 'Going on all day,',
	bannerTextPart2 : 'Going on all night!',
	bannerSideHead : 'We Work',
	bannerSidePara : 'Solving complex, algorithmic, engineering problem is our passion. We follow traditional waterfall as well as agile development processes depending on the nature and the need of the project.Whether you are an established company or a start-up, with our skills, expertise and passion, we can definitely add a great value to your organization.',
	feature1Img : 'images/whatWeDo/1.png',
	feature2Img : 'images/whatWeDo/2.png',
	feature3Img : 'images/whatWeDo/3.png',
	feature4Img : 'images/whatWeDo/4.png',
	feature5Img : 'images/whatWeDo/5.png',
	feature1HeadPart1 : 'Mobile',
	feature1HeadPart2 : 'Development',
	feature2HeadPart1 : 'Web',
	feature2HeadPart2 : 'Development',
	feature3HeadPart1 : 'Graphics',
	feature3HeadPart2 : 'Design',
	feature4HeadPart1 : 'Mobile',
	feature4HeadPart2 : 'Games.',
	feature5HeadPart1 : 'Customized',
	feature5HeadPart2 : 'Software',
	feature1Para : 'Mobile is becoming not only the new digital hub but also the bridge to the physical world. That’s why mobile will affect more than just your digital operations – it will transform your entire business.',
	feature2Para : 'Not every website is created equal. Building a website is easy, building an effective website that will help your business foster a pipeline of new leads and customers is a very difficult task.',
	feature3Para : 'There is no limit to what you can get designed at Bolt Infotech. Whether you are looking for a spectacular new logo or Ui Ux design or some stunning flyers, the talented community of designers here can make it happen.',
	feature4Para : 'Our expert developers follow some of the newest development methodologies for delivering next level mobile gaming experience. Creating fun games that never get old is our main focus! Everything else is just icing on the cake',
	feature5Para : 'Software is the magic thing whose importance only goes up over time. We love creating such magic factors. Solving complex, algorithmic, engineering problem is our passion.Our team of software engineers is always keen to take on the next challenge',
	cardHeadPart1 : 'We Elevate ',
	cardHeadPart2 : ' Your Brand!',
	card1Img: 'images/whatWeDo/6.png',
	card2Img: 'images/whatWeDo/7.png',
	card3Img: 'images/whatWeDo/8.png',
	card1HeadPart1: 'Speak ',
	card1HeadPart2: 'Your Culture',
	card2HeadPart1: 'Offer ',
	card2HeadPart2 : 'Full Support',
	card3HeadPart1: 'Pleasing ',
	card3HeadPart2: 'Customers',
	card1Para: 'Seeing the clients passionate about their idea makes us excited. We always look for new ways to provide solutions and create a better product',
	card2Para: 'Our expert team of advisors will identify and study the challenges, bringing solutions to ensure a smooth and efficient running of your business.',
	card3Para : 'Consumers drive the business. That’s why we take an extra leap to produce stunning apps and websites for your end users, focused towards increasing sales and brand visibility.',
	belowCtah1:"Wanna Collaborate?",
	belowCtah2:"It will be fun transforming your idea digitally."
}