module.exports = {
    //hide download btn
	downloadBtnHide : ' ',
	//section or element hide data
	modalBtnHide : 'display:none;',
	//img2 css patch
	cssPatch : '',
	//section or element hide data
	btnHide : 'display:none;',
	modalBtnAction: ' ',
	sectionHide : 'display:none;',
	feature1Hide : ' ',
	feature2Hide : ' ',
	feature3Hide : ' ',
	feature4Hide : ' ',
	feature5Hide : 'display:none',
	//navbar active
	activeAbout : ' ',
	activeWhatWeDo : ' ',
	activeBlogs : '',
	activeOurWork : '',
	activeCareers : '',
	activeWorkshops : 'active',
	activeSchoolManagementSystem: '',
	//button route
	btn1route : ' ',
	btn2route : ' ',
	btn3route : ' ',
	btn4route : ' ',
	btn5route : ' ',
	//button text
	btn1text : 'Download Brochure',
	btn2text : 'Download Brochure',
	btn3text : 'Download Brochure',
	btn4text : 'Download Brochure',
	btn5text : 'Download Brochure',
	btn6text : 'Download Brochure',
	btn7text : 'Download Brochure',
	btn8text : 'Download Brochure',
	//display data
	bannerImg: 'images/workshops/banner.png',
	bannerTextPart1 : 'Get',
	bannerTextPart2 : 'INDUSTRY READY!',
	bannerSideHead : 'Learn Pragmatically..',
	bannerSidePara : "We give the complete practical insights of the stated topics in our Development workshop, providing the students, an opportunity to learn the latest technologies on the top of cutting edge tech stacks, by our Industry Experts. Students get a chance to work on live projects and even make a complete project from scratch in our Worksops. We also provide knowledge on project management strategies including Git Version Control and Agile Working Methodology in our Training Sessions.",
	feature1Img : 'images/workshops/1.png',
	feature2Img : 'images/workshops/2.png',
	feature3Img : 'images/workshops/3.png',
	feature4Img : 'images/workshops/4.png',
	feature5Img : 'images/workshops/5.png',
	feature1HeadPart1 : 'Mobile development',
	feature1HeadPart2 : 'WORKSHOPS',
	feature2HeadPart1 : 'Web development',
	feature2HeadPart2 : 'WORKSHOPS',
	feature3HeadPart1 : 'Graphics designing',
	feature3HeadPart2 : 'WORKSHOPS',
	feature4HeadPart1 : 'Game development',
	feature4HeadPart2 : 'WORKSHOPS',
	feature5HeadPart1 : 'Back-end development',
	feature5HeadPart2 : 'WORKSHOPS',
	feature1Para : 'Have got amazing work experience on Android Development, iOS development, Java, Kotlin, Objective-C, Swift, Xcode, React Native or Flutter? Apply now! We will look into your past projects and knowledge base before giving you a call.',
	feature2Para : 'More than confident for coding backend APIs on ASP .NET, PHP, NodeJs, Python? Have you got knowledge of the latest front-end tech stacks including SASS, Advanced CSS, jQuery and HTML5? Love integrating CMS efficiently? Apply now!',
	feature3Para : 'The sky is the limit for your creativity? Have you got an amazing color sense and theming concepts? Got expertise working on Adobe CC applications? (Confident working on any one of them or more?) Provide links to your works in your Resume and Apply now!',
	feature4Para : 'Best aware of all technical aspects of the game development including challenges in implementing the core game mechanics, art, animation? Can optimize code for the best possible performance, quality, and responsiveness of games across platforms? Hit the button below.',
	cardHeadPart1 : 'Automobile ',
	cardHeadPart2 : 'Workshops',
	card1Img: 'images/workshops/6.png',
	card2Img: 'images/workshops/7.png',
	card3Img: 'images/workshops/8.png',
	card1HeadPart1: 'Car ',
	card1HeadPart2: 'Overhauling',
	card2HeadPart1: 'Motor Cycle ',
	card2HeadPart2 : 'Overhauling',
	card3HeadPart1: 'Engine ',
	card3HeadPart2: 'Overhauling',
	card1Para: 'Our work environment never restricts your creativity and we provide completely free canvas to you to paint and create your best picture!',
	card2Para: 'We ensure standing side by side with you with our team in all moments of Happiness and sorrow. We believe in woking and growing together.',
	card3Para : "We've built this business with the passion for innovation and a flexible approach in what we do. That's why we keep our eyes and ears open for smart people who get things done."
}